Update check_folders.yml

diff --git a/.github/workflows/check_folders.yml b/.github/workflows/check_folders.yml
--- a/.github/workflows/check_folders.yml
+++ b/.github/workflows/check_folders.yml
@@ -14,8 +14,10 @@ jobs:
 
     - name: Check for required folders and files
       run: |
-        # Check for file renames in the pull request diff
-        if git diff --name-status ${{ github.base_ref }}..${{ github.sha }} | grep -q '^R'; then
-          echo "Error: File renames are not allowed in this repository."
-          exit 1
+        development_branch="development"
+        
+        # Check if the folder name has been changed or deleted in the created branch
+        if git diff --name-only --diff-filter=RD $development_branch...${{ github.ref }} | grep -q '^dbt_project.yml$'; then
+          echo "Folder name 'dbt_project.yml' has been changed or deleted in the created branch."
+          exit 1  # Fail the workflow
         fi
