Update check_folders.yml

diff --git a/.github/workflows/check_folders.yml b/.github/workflows/check_folders.yml
--- a/.github/workflows/check_folders.yml
+++ b/.github/workflows/check_folders.yml
@@ -14,8 +14,16 @@ jobs:
 
     - name: Check for required folders and files
       run: |
-        # Check if folder macros exists
-        if [ ! -d "macros" ]; then
-          echo "Folder macros is missing."
+        # Check if folder models exists
+        if [ -d "models" ]; then
+          # Check if folders Datamart, Integration, Staging and Raw exist inside folder models
+          if [ -d "models/Datamart" ] ; then
+            echo "Folders Datamart, Integration, Staging and Raw are present inside folder models."
+          else
+            echo "One or more of the folders Datamart, Integration, Staging and Raw are missing inside folder models."
+            exit 1  # Fail the workflow
+          fi
+        else
+          echo "Folder models is missing."
           exit 1  # Fail the workflow
         fi
